package hep.dataforge.meta.descriptors

import hep.dataforge.meta.*
import hep.dataforge.names.NameToken

/**
 * A [Meta] that is constructed from [NodeDescriptor]
 */
private class DescriptorMeta(val descriptor: NodeDescriptor) : Meta, MetaBase() {
    override val items: Map<NameToken, MetaItem>
        get() = buildMap {
            descriptor.items.forEach { (token, descriptorItem) ->
                val item = descriptorItem.defaultItem()
                if (item != null) {
                    put(NameToken(token), item)
                }
            }
        }
}

/**
 * Generate a laminate representing default item set generated by this descriptor
 */
public fun NodeDescriptor.defaultMeta(): Laminate = Laminate(default, DescriptorMeta(this))

/**
 * Build a default [NodeItem] from this node descriptor
 */
internal fun NodeDescriptor.defaultItem(): NodeItem<*> =
    NodeItem(defaultMeta())

/**
 * Build a default [ValueItem] from this descriptor
 */
internal fun ValueDescriptor.defaultItem(): ValueItem? {
    return ValueItem(default ?: return null)
}

/**
 * Build a default [TypedMetaItem] from descriptor.
 */
public fun ItemDescriptor.defaultItem(): MetaItem? {
    return when (this) {
        is ValueDescriptor -> defaultItem()
        is NodeDescriptor -> defaultItem()
    }
}